# Site settings
title: dce4's blog
description:
lang: en-US
timezone: Asia/Istanbul
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo:
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: dce4
  bio: <a href="https://github.com/dce4" id="logo"><img src="/assets/img/github.png"></a>
       <a href="https://linkedin.com/in/dce4" id="logo"><img src="/assets/img/linkedin.png"></a>
       <a href="https://twitter.com/dce4_" id="logo"><img src="/assets/img/twitter.png"></a>
  username: username
  email:
  avatar: /assets/img/avatar.png

# Url settings
url: "dce4.me"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
